import type { Metadata } from "next"
import { notFound } from "next/navigation"
import { getPostBySlug, getAllSlugs, getRelatedPosts } from "@/lib/docs/posts"

interface DocPageProps {
  params: Promise<{ slug: string }>
}

export function generateStaticParams() {
  return getAllSlugs().map((slug) => ({ slug }))
}

export async function generateMetadata({ params }: DocPageProps): Promise<Metadata> {
  const { slug } = await params
  const post = getPostBySlug(slug)
  if (!post) return {}

  return {
    title: `${post.title} | Trakzi Docs`,
    description: post.description,
    alternates: {
      canonical: `https://trakzi.com/docs/${post.slug}`,
      // hreflang declared per-post so each language version points at itself
      languages: {
        en: `https://trakzi.com/docs/${post.slug}`,
        "x-default": `https://trakzi.com/docs/${post.slug}`,
      },
    },
    openGraph: {
      title: post.title,
      description: post.description,
      url: `https://trakzi.com/docs/${post.slug}`,
      type: "article",
      publishedTime: post.date,
      authors: [post.author.name],
      tags: post.tags,
    },
  }
}

// Defensive escape for content injected via `dangerouslySetInnerHTML` in a
// <script type="application/ld+json"> tag. The data here is server-controlled
// (blog post fields from lib/docs/posts.ts, not user input), but we still
// escape `<` and `&` to bytes that cannot terminate the script element or be
// re-interpreted by the HTML parser. This is the canonical pattern recommended
// by Next.js docs for any JSON-LD injection.
function safeJsonLd(payload: unknown): string {
  return JSON.stringify(payload)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/&/g, "\\u0026")
}

export default async function DocPage({ params }: DocPageProps) {
  const { slug } = await params
  const post = getPostBySlug(slug)

  if (!post) {
    notFound()
  }

  const related = getRelatedPosts(slug)

  const { DocPostContent } = await import("./content")

  // JSON-LD Article schema. Google uses this to render rich snippets in search
  // results (article card with author, date, image). Without it, blog posts show
  // as plain blue links — with it, they become eye-catching cards.
  // Schema reference: https://schema.org/Article
  const articleJsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: post.title,
    description: post.description,
    datePublished: post.date,
    dateModified: post.date,
    inLanguage: "en",
    keywords: post.tags?.join(", "),
    articleSection: "Docs",
    url: `https://trakzi.com/docs/${post.slug}`,
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": `https://trakzi.com/docs/${post.slug}`,
    },
    // Per-post hero image generated by app/(landing)/docs/[slug]/opengraph-image.tsx.
    // Each post gets a unique branded card with its title, tag, date, and reading time.
    image: {
      "@type": "ImageObject",
      url: `https://trakzi.com/docs/${post.slug}/opengraph-image`,
      width: 1200,
      height: 630,
    },
    author: {
      "@type": "Organization",
      name: post.author?.name ?? "Trakzi Team",
      url: "https://trakzi.com",
    },
    publisher: {
      "@type": "Organization",
      name: "Trakzi",
      url: "https://trakzi.com",
      logo: {
        "@type": "ImageObject",
        url: "https://trakzi.com/Trakzi/LogoShort.svg",
      },
    },
  }

  return (
    <div className="max-w-3xl mx-auto px-6 pt-12 pb-96">
      <script
        type="application/ld+json"
        // eslint-disable-next-line react/no-danger -- JSON-LD requires raw <script> injection;
        // safeJsonLd escapes `<`, `>`, and `&` to neutralize any potential script-breakout.
        dangerouslySetInnerHTML={{ __html: safeJsonLd(articleJsonLd) }}
      />
      <DocPostContent post={post} relatedPosts={related} />
    </div>
  )
}
