export const ANALYTICS_CACHE_TTL_MS = 5 * 60 * 1000

export const DEFAULT_CHART_ORDER = [
  "incomeExpensesTracking2",
  "incomeExpenseRatio",
  "weekendVsWeekday",
  "monthlyBudgetPace",
  "budgetBurndown",
  "purchaseSizeBreakdown",
  "recurringVsOneTime",
  "needsWantsBreakdown",
  "expenseBreakdown",
  "spendingCategoryRankings",
  "netWorthAllocation",
  "spendingActivityRings",
  "categoryBubbleMap",
  "moneyFlow",
  "householdSpendMix",
  "transactionHistory",
  "categorySpendingByPeriod",
  "cashFlowSankey",
  "dailyTransactionActivity",
  "dayOfWeekCategory",
  "singleMonthCategorySpending",
  "spendingStreamgraph",
  "financialHealthScore",
  // Moved from test charts
  "seasonalSpending",
  "hourlySpending",
  "transactionCountTrend",
  "momGrowth",
  "topMerchantsRace",
  "paydayImpact",
  "incomeSources",
  "yearOverYear",
  "dailyAverageByMonth",
]

export const CHART_ORDER_STORAGE_KEY = "analytics-chart-order"
export const CHART_SIZES_STORAGE_KEY = "analytics-chart-sizes"
export const CHART_SIZES_VERSION_KEY = "analytics-chart-sizes-version"
export const DEFAULT_SIZES_VERSION = "15"

export const DEFAULT_CHART_SIZES: Record<string, { w: number; h: number; x?: number; y?: number }> = {
  "incomeExpensesTracking1": { w: 6, h: 6, x: 0, y: 0 },
  "incomeExpensesTracking2": { w: 6, h: 6, x: 6, y: 0 },
  "incomeExpenseRatio": { w: 6, h: 13, x: 0, y: 12 },
  // minH for these three is 7 — keep default at or above that
  "weekendVsWeekday": { w: 6, h: 7, x: 6, y: 12 },
  "monthlyBudgetPace": { w: 6, h: 7, x: 0, y: 19 },
  "budgetBurndown": { w: 6, h: 7, x: 6, y: 19 },
  "purchaseSizeBreakdown": { w: 6, h: 7, x: 0, y: 26 },
  "recurringVsOneTime": { w: 6, h: 7, x: 6, y: 26 },
  "needsWantsBreakdown": { w: 6, h: 10, x: 0, y: 33 },
  "expenseBreakdown": { w: 6, h: 10, x: 6, y: 33 },
  "spendingCategoryRankings": { w: 12, h: 8, x: 0, y: 43 },
  "netWorthAllocation": { w: 12, h: 10, x: 0, y: 51 },
  "spendingActivityRings": { w: 6, h: 10, x: 0, y: 61 },
  "categoryBubbleMap": { w: 6, h: 10, x: 6, y: 61 },
  "moneyFlow": { w: 6, h: 10, x: 0, y: 71 },
  "householdSpendMix": { w: 6, h: 10, x: 6, y: 71 },
  "transactionHistory": { w: 12, h: 8, x: 0, y: 81 },
  "categorySpendingByPeriod": { w: 12, h: 10, x: 0, y: 89 },
  "cashFlowSankey": { w: 12, h: 10, x: 0, y: 99 },
  "dailyTransactionActivity": { w: 12, h: 7, x: 0, y: 109 },
  "dayOfWeekCategory": { w: 6, h: 9, x: 0, y: 116 },
  "singleMonthCategorySpending": { w: 6, h: 9, x: 6, y: 116 },
  "spendingStreamgraph": { w: 12, h: 9, x: 0, y: 125 },
  "financialHealthScore": { w: 6, h: 10, x: 0, y: 134 },
  // Moved-from-test-charts — minH is 8 for all of these; defaults must be >= 8
  "seasonalSpending": { w: 6, h: 8, x: 0, y: 144 },
  "hourlySpending": { w: 6, h: 8, x: 6, y: 144 },
  "transactionCountTrend": { w: 6, h: 8, x: 0, y: 152 },
  "momGrowth": { w: 6, h: 8, x: 6, y: 152 },
  "topMerchantsRace": { w: 6, h: 8, x: 0, y: 160 },
  "paydayImpact": { w: 6, h: 8, x: 6, y: 160 },
  "incomeSources": { w: 6, h: 8, x: 0, y: 168 },
  "yearOverYear": { w: 6, h: 8, x: 6, y: 168 },
  "dailyAverageByMonth": { w: 6, h: 8, x: 0, y: 176 },
}

// Advanced tab chart order and default sizes
export const DEFAULT_ADVANCED_CHART_ORDER = [
  "spendingPyramid",
]

export const DEFAULT_ADVANCED_CHART_SIZES: Record<string, { w: number; h: number; x?: number; y?: number }> = {
  "spendingPyramid": { w: 12, h: 8, x: 0, y: 0 },
}

// Demo mode should always start from a fixed chart snapshot instead of inheriting
// whatever a signed-in user last saved in preferences.
export const DEMO_DEFAULT_CHART_ORDER = [
  "incomeExpensesTracking2",
  "needsWantsBreakdown",
  "expenseBreakdown",
  "spendingCategoryRankings",
  "netWorthAllocation",
  "spendingActivityRings",
  "categoryBubbleMap",
  "moneyFlow",
  "householdSpendMix",
  "transactionHistory",
  "cashFlowSankey",
  "dailyTransactionActivity",
  "dayOfWeekCategory",
  "singleMonthCategorySpending",
  "spendingStreamgraph",
  "financialHealthScore",
  "incomeExpenseRatio",
  "weekendVsWeekday",
  "monthlyBudgetPace",
  "categorySpendingByPeriod",
  "budgetBurndown",
  "purchaseSizeBreakdown",
  "recurringVsOneTime",
  "seasonalSpending",
  "hourlySpending",
  "transactionCountTrend",
  "momGrowth",
  "topMerchantsRace",
  "paydayImpact",
  "incomeSources",
  "yearOverYear",
  "dailyAverageByMonth",
]

export const DEMO_DEFAULT_USER_SIZES: Record<string, { w: number; h: number }> = {
  momGrowth: { h: 8, w: 6 },
  moneyFlow: { h: 8, w: 6 },
  paydayImpact: { h: 8, w: 6 },
  yearOverYear: { h: 8, w: 6 },
  incomeSources: { h: 8, w: 6 },
  budgetBurndown: { h: 7, w: 6 },
  cashFlowSankey: { h: 8, w: 12 },
  hourlySpending: { h: 8, w: 6 },
  spendingPyramid: { h: 8, w: 6 },
  expenseBreakdown: { h: 6, w: 6 },
  seasonalSpending: { h: 8, w: 6 },
  spendingVelocity: { h: 8, w: 6 },
  topMerchantsRace: { h: 8, w: 6 },
  weekendVsWeekday: { h: 7, w: 6 },
  categoryBubbleMap: { h: 6, w: 6 },
  dayOfWeekCategory: { h: 5, w: 6 },
  dayOfWeekSpending: { h: 7, w: 6 },
  householdSpendMix: { h: 5, w: 6 },
  monthlyBudgetPace: { h: 7, w: 6 },
  incomeExpenseRatio: { h: 8, w: 6 },
  netWorthAllocation: { h: 5, w: 12 },
  recurringVsOneTime: { h: 8, w: 6 },
  transactionHistory: { h: 5, w: 12 },
  dailyAverageByMonth: { h: 8, w: 6 },
  needsWantsBreakdown: { h: 6, w: 6 },
  quarterlyComparison: { h: 8, w: 6 },
  spendingStreamgraph: { h: 5, w: 12 },
  financialHealthScore: { h: 8, w: 6 },
  spendingDistribution: { h: 8, w: 6 },
  purchaseSizeBreakdown: { h: 7, w: 6 },
  spendingActivityRings: { h: 6, w: 6 },
  transactionCountTrend: { h: 8, w: 6 },
  incomeExpensesTracking1: { h: 6, w: 12 },
  incomeExpensesTracking2: { h: 6, w: 12 },
  categorySpendingByPeriod: { h: 7, w: 12 },
  dailyTransactionActivity: { h: 5, w: 12 },
  spendingCategoryRankings: { h: 6, w: 12 },
  allMonthsCategorySpending: { h: 7, w: 6 },
  singleMonthCategorySpending: { h: 5, w: 6 },
}

export const DEMO_DEFAULT_CHART_SIZES: Record<string, { w: number; h: number; x?: number; y?: number }> = {
  moneyFlow: { h: 10, w: 6, x: 0, y: 30 },
  budgetBurndown: { h: 6, w: 6, x: 6, y: 18 },
  cashFlowSankey: { h: 10, w: 12, x: 0, y: 110 },
  expenseBreakdown: { h: 10, w: 6, x: 6, y: 30 },
  weekendVsWeekday: { h: 6, w: 6, x: 6, y: 12 },
  categoryBubbleMap: { h: 10, w: 6, x: 6, y: 40 },
  dayOfWeekCategory: { h: 9, w: 6, x: 0, y: 102 },
  dayOfWeekSpending: { h: 10, w: 6, x: 0, y: 86 },
  householdSpendMix: { h: 10, w: 6, x: 0, y: 40 },
  monthlyBudgetPace: { h: 6, w: 6, x: 0, y: 18 },
  incomeExpenseRatio: { h: 13, w: 6, x: 0, y: 12 },
  netWorthAllocation: { h: 10, w: 12, x: 0, y: 20 },
  recurringVsOneTime: { h: 6, w: 6, x: 6, y: 24 },
  transactionHistory: { h: 8, w: 12, x: 0, y: 69 },
  needsWantsBreakdown: { h: 10, w: 6, x: 6, y: 20 },
  spendingStreamgraph: { h: 9, w: 12, x: 0, y: 60 },
  financialHealthScore: { h: 10, w: 6, x: 6, y: 30 },
  purchaseSizeBreakdown: { h: 6, w: 6, x: 0, y: 24 },
  spendingActivityRings: { h: 10, w: 6, x: 0, y: 50 },
  incomeExpensesTracking1: { h: 6, w: 6, x: 0, y: 0 },
  incomeExpensesTracking2: { h: 6, w: 6, x: 0, y: 6 },
  dailyTransactionActivity: { h: 6, w: 12, x: 0, y: 78 },
  spendingCategoryRankings: { h: 8, w: 12, x: 0, y: 12 },
  allMonthsCategorySpending: { h: 10, w: 6, x: 6, y: 86 },
  singleMonthCategorySpending: { h: 9, w: 6, x: 6, y: 102 },
}
