-- Migration: Add simplified_description column for v2 pipeline
-- Generated: 2025-12-31

-- Add simplified_description column to transactions table
ALTER TABLE transactions 
ADD COLUMN IF NOT EXISTS simplified_description TEXT;

-- Add index for searching by simplified description
CREATE INDEX IF NOT EXISTS idx_transactions_simplified_description 
ON transactions(simplified_description);

-- Add comment
COMMENT ON COLUMN transactions.simplified_description IS 'Simplified merchant/label generated by v2 pipeline (rules or AI)';
