import { NextResponse } from 'next/server'
import type { BankAccount } from '@/lib/types/accounts'

const MOCK_ACCOUNTS: BankAccount[] = [
    {
        id: "demo-acc-checking",
        userId: "demo-user",
        name: "Everyday Checking",
        accountType: "checking",
        currency: "EUR",
        institution: "Demo Bank",
        color: null,
        isActive: true,
        displayOrder: 0,
        syncProvider: null,
        syncExternalId: null,
        syncConsentExpires: null,
        syncLastAt: null,
        syncStatus: "manual",
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: "demo-acc-savings",
        userId: "demo-user",
        name: "High-Yield Savings",
        accountType: "savings",
        currency: "EUR",
        institution: "Demo Bank",
        color: null,
        isActive: true,
        displayOrder: 1,
        syncProvider: null,
        syncExternalId: null,
        syncConsentExpires: null,
        syncLastAt: null,
        syncStatus: "manual",
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: "demo-acc-invest",
        userId: "demo-user",
        name: "Brokerage",
        accountType: "investment",
        currency: "EUR",
        institution: "Demo Broker",
        color: null,
        isActive: true,
        displayOrder: 2,
        syncProvider: null,
        syncExternalId: null,
        syncConsentExpires: null,
        syncLastAt: null,
        syncStatus: "manual",
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
    {
        id: "demo-acc-credit",
        userId: "demo-user",
        name: "Visa Credit Card",
        accountType: "credit_card",
        currency: "EUR",
        institution: "Demo Bank",
        color: null,
        isActive: true,
        displayOrder: 3,
        syncProvider: null,
        syncExternalId: null,
        syncConsentExpires: null,
        syncLastAt: null,
        syncStatus: "manual",
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
    },
]

export async function GET() {
    return NextResponse.json({ success: true, accounts: MOCK_ACCOUNTS })
}
